services:
  mysql:
    image: mysql:8.4.2
    shm_size: 128mb
    tmpfs: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 2s
      retries: 10
  example-db:
    image: mysql:8.4.2
    shm_size: 128mb
    tmpfs: /var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 2s
      retries: 10
  postgres:
    image: postgres:16.3
    shm_size: 128mb
    tmpfs: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 2s
      retries: 10
